description: "This site is created for 2 purposes: 1) Practice making websites with Jekyll and GitHub Pages for DSC onboarding and 2) document Loretta's personal reading journey"
email: "lorettahu09@gmail.com"
instagram: "https://www.instagram.com/lorhu09/" 

books:
  -
    title: "The Library Book"
    author: "Susan Orlean"
    genre: "non-fiction" 
    start_date: "2023-06-06"
  -
    title: "Poisonwood Bible"
    author: "Barbara Kingsolver"
    genre: "fiction" 
    start_date: "2020-07-31"
  -
    title: "The Summer Book"
    author: "Tove Jansson"
    genre: "fiction" 
    start_date: "2022-06-09"
