description: "This site is created for 2 purposes: 1) Practice making websites with Jekyll and GitHub Pages for DSC onboarding and 2) document Loretta's personal reading journey"
email: "lorettahu09@gmail.com"
Instagram: "https://www.instagram.com/lorhu09/" 
